### ISSUE TITLE
Lessons Learned Feedback from JH

### ISSUE THREAD

**Issue by zpdeering** [microsoft/XNAT-on-Azure#2]
I just wanted to suggest some improvements to the XNAT Docker implementation, based on what we learned while deploying to the JH environment:

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/Dockerfile#L6
This should be under XNAT_ROOT (e.g. /data/xnat/home)

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/Dockerfile#L11
Because of the way Docker containers are built in layers that are cached, this line should be much lower in the Dockerfile so that if the script changes, the rest of the container will be able to be loaded from the cache if there are no other changes.

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/Dockerfile#L12
This will install the latest PSQL client. It needs to match the version of PSQL that you're connecting to instead.

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/Dockerfile#L16-L19
These folders should not be created here, as they're being made before the external storage is attached to the container so they won't persist. They should be added to the run.sh file instead.

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/Dockerfile#L25
Since this plugin persists outside of the actual XNAT install, it should probably be managed separately from the Docker/start scripts. This would also allow for upgrades to the plugin without rebuilding and redeploying the container.

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/docker/xnat/run.sh#L54-L55
What is the purpose of copying the config directory? That new folder only lives on the container and isn't referenced anywhere.

https://github.com/microsoft/XNAT-on-Azure/blob/c1613cbd62961bf7f7b23f54da9eaa325f608204/src/arm/xnat.ui.json#L113
This needs to live under XNAT_ROOT (similar to the first improvement note)

**Comment by ganeshiyer-ms** [comment]
Hi @zpdeering, thanks so much! This is excellent feedback. I've created a PR and incorporated these changes. We're still thinking about the best way to manage the plugins, so I'll address that in a separate PR.
